name: Android Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12"
          cache: 'gradle'

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0"
          channel: 'stable'
          cache: true

      # Debug npm and semver versions
      - name: Debug npm and semver
        run: |
          echo "NPM Version:"
          npm --version
          echo "Semver Info:"
          npm info semver

      # Clean npm cache
      - name: Clean npm cache
        run: npm cache clean --force

      # Upgrade Flutter
      - name: Flutter Upgrade
        run: flutter upgrade --force

      # Install dependencies
      - name: Get Dependencies
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk

      # Upload APK
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
